[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font"

[window]
padding.x = 10
padding.y = 10
opacity = 0.85
blur = true
decorations = "Buttonless"
dimensions.columns = 144
dimensions.lines = 50
