import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font"

[window]
padding.x = 10
padding.y = 10
opacity = 0.85
blur = true
decorations = "Buttonless"
dimensions.columns = 144
dimensions.lines = 50
